version: 0.0
os: linux
files:
  - source: /docker-compose.yml
    destination: /home/assignment/
  - source: /run_container.sh
    destination: /home/assignment/
  - source: /.env
    destination: /home/assignment/
permissions:
  - object: /home/assignment/
    owner: root
    group: root
    mode: 770
hooks:
  AfterInstall:
    - location: /run_container.sh
      timeout: 600
      runas: root
  