version: 0.0
os: linux
files:
  - source: /
    destination: /home/assignment/
permissions:
  - object: /home/assignment/
    owner: root
    group: root
    mode: 770
hooks:
  AfterInstall:
    - location: /run_container.sh
      timeout: 300
      runas: root
  