version: 0.2

phases:
    install:
        commands:
            - echo Nothing to do in the install phase...
    pre_build:
        commands:
            - echo Nothing to do in the pre_build phase...
    build:
        commands:
            - echo Build started on `date`
            - echo Building Docker Image
            - docker-compose build
            - python3 -m unittest discover /tests
            - docker login --username mustafakmal --password mustafa@7890
            - docker push mustafakmal/assignment:latest
    post_build:
        commands:
            - echo Build completed on `date`